export default [
  {
    id: 1,
    name: "Bertie Yates",
    age: 29,
    image: "https://www.course-api.com/images/people/person-1.jpeg",
    birthDay: 23,
    birthMonth: "September",
  },
  {
    id: 2,
    name: "Hester Hogan",
    age: 32,
    image: "https://www.course-api.com/images/people/person-2.jpeg",
    birthDay: 3,
    birthMonth: "January",
  },
  {
    id: 3,
    name: "Larry Little",
    age: 36,
    image: "https://www.course-api.com/images/people/person-3.jpeg",
    birthDay: 23,
    birthMonth: "September",
  },
  {
    id: 4,
    name: "Sean Walsh",
    age: 34,
    image: "https://www.course-api.com/images/people/person-4.jpeg",
    birthDay: 8,
    birthMonth: "September",
  },
  {
    id: 5,
    name: "Lola Gardner",
    age: 29,
    image: "https://www.course-api.com/images/people/person-5.jpeg",
    birthDay: 22,
    birthMonth: "October",
  },
];
export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];
